module.exports = {
  content: ["./app/**/*.{ts,tsx,js,jsx}", "./components/**/*.{ts,tsx,js,jsx}"],
  theme: {
    extend: {
      colors: {
        /* map Figma tokens to utility color names used in your components */
        "surface-base": "var(--surface-base)",
        "surface-card": "var(--surface-card)",
        "surface-hover": "var(--gray-100)",
        "text-primary": "var(--text-primary)",
        "text-secondary": "var(--text-secondary)",
        "border-subtle": "var(--border-subtle)",
        brand: "var(--primary)",
        primary: "var(--primary)",
        "primary-foreground": "#FFFFFF",
        secondary: "var(--secondary)",
        "secondary-foreground": "#FFFFFF",
        accent: "var(--accent)",
        "accent-foreground": "#FFFFFF",
        destructive: "#EF4444",
        "destructive-foreground": "#FFFFFF",
        warning: "#F87171",
        "warning-light": "#FCA5A5",
        neutral: "#C4B5FD",
        "neutral-light": "#DDD6FE",
        bg: "var(--background)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        card: "var(--card)",
        "card-foreground": "var(--card-foreground)",
        border: "var(--border)",
        muted: "var(--muted)",
        "muted-foreground": "var(--muted-foreground)",
        panel: "var(--panel-tint)",
        "panel-border": "var(--panel-border)",
        chip: "var(--chip-bg)",
        "chip-icon": "var(--chip-icon)",
      },
      fontFamily: {
        sans: ["var(--font-sans)"],
        display: ["var(--font-display)"],
      },
      borderRadius: { xl2: "16px" },
      boxShadow: {
        smx: "var(--shadow-sm)",
        mdx: "var(--shadow-md)",
        lgx: "var(--shadow-lg)",
        ring: "var(--ring)",
      },
    },
  },
  plugins: [],
};
